# Generated by Django 5.2.7 on 2025-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_status_wholesaleorderitem_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_delivery_date",
            field=models.DateTimeField(
                blank=True,
                help_text="For offline orders: The scheduled date/time for pickup or delivery.",
                null=True,
            ),
        ),
    ]
