# Generated by Django 5.2.7 on 2025-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="availability_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the item will be available if out of stock.",
                null=True,
            ),
        ),
    ]
