# Generated by Django 5.2.7 on 2025-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerprofile",
            name="shop_address",
            field=models.CharField(
                blank=True, help_text="Full address for geocoding", max_length=255
            ),
        ),
    ]
